# Generated by Django 5.0.7 on 2024-08-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
