# Generated by Django 5.0.7 on 2024-08-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
